require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/health_symptoms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # HealthSymptom. As you add validations to HealthSymptom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:health_symptom)
  }

  let(:invalid_attributes) {
    attributes_for(:health_symptom, sintoma: nil)
  }

  describe "GET /index" do
    it "renders a successful response" do
      HealthSymptom.create! valid_attributes
      get health_symptoms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      health_symptom = HealthSymptom.create! valid_attributes
      get health_symptom_url(health_symptom)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_health_symptom_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      health_symptom = HealthSymptom.create! valid_attributes
      get edit_health_symptom_url(health_symptom)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HealthSymptom" do
        expect {
          post health_symptoms_url, params: { health_symptom: valid_attributes }
        }.to change(HealthSymptom, :count).by(1)
      end

      it "redirects to the created health_symptom" do
        post health_symptoms_url, params: { health_symptom: valid_attributes }
        expect(response).to redirect_to(health_symptom_url(HealthSymptom.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HealthSymptom" do
        expect {
          post health_symptoms_url, params: { health_symptom: invalid_attributes }
        }.to change(HealthSymptom, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post health_symptoms_url, params: { health_symptom: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        attributes_for(:health_symptom, intensidade: :moderado)
      }

      it "updates the requested health_symptom" do
        health_symptom = HealthSymptom.create! valid_attributes
        patch health_symptom_url(health_symptom), params: { health_symptom: new_attributes }
        health_symptom.reload
        expect(health_symptom.intensidade).to eq("moderado")
      end

      it "redirects to the health_symptom" do
        health_symptom = HealthSymptom.create! valid_attributes
        patch health_symptom_url(health_symptom), params: { health_symptom: new_attributes }
        health_symptom.reload
        expect(response).to redirect_to(health_symptom_url(health_symptom))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        health_symptom = HealthSymptom.create! valid_attributes
        patch health_symptom_url(health_symptom), params: { health_symptom: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested health_symptom" do
      health_symptom = HealthSymptom.create! valid_attributes
      expect {
        delete health_symptom_url(health_symptom)
      }.to change(HealthSymptom, :count).by(-1)
    end

    it "redirects to the health_symptoms list" do
      health_symptom = HealthSymptom.create! valid_attributes
      delete health_symptom_url(health_symptom)
      expect(response).to redirect_to(health_symptoms_url)
    end
  end
end
